#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /opt/rdpgw s6-setuidgid abc /opt/rdpgw/rdpgw -c /config/rdpgw.yaml
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            cd /opt/rdpgw /opt/rdpgw/rdpgw -c /config/rdpgw.yaml
fi